# Your presentation title
title: Oliver Hoffmann

# The Reveal theme
reveal_theme: white.css

# The Reveal transition
reveal_transition: default

# Path to the used theme (defaults to the Reveal.js standard theme path)
reveal_theme_path: reveal.js/css/theme/ 

# Embed Server-side speaker notes?
reveal_notes_server: false

# Additional reveal.js options
reveal_options:
    - 'width: "320px"'
    - 'height: "320px"'

# Additional reveal.js dependencies
reveal_dependencies: 

# Reveal.js subdirectory
reveal_path: reveal.js/

# Don't change anything below
markdown: redcarpet
# highlighter: pygments
markdown_ext: ignoreme

